FROM node:7.10

MAINTAINER Denis Ma

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
RUN npm install
#COPY ../../backend/ /usr/src/app
#EXPOSE 3000
#CMD [ “npm”, “start” ]
